[MusicBot]
# 初期音量（0.0～2.0の範囲で指定）
default_volume = 0.25
# キューの最大数（曲の追加制限）
default_queue_limit = 50
# プレイリストの最大数（ユーザーごとの保存制限）
default_playlist_limit = 10
# ブラウザ偽装の際に渡すカスタムヘッダー（アクセス制限回避用）
user_agent = "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
# SQLiteデータベースのファイルパス
database_path = data.db