import asyncio
import os
import time
from typing import List, Dict
from playwright.async_api import async_playwright, BrowserContext

class CookieManager:
	"""
	Playwrightを使用して各サイトのCookieを取得・管理するクラス。
	"""

	def __init__(self, storage_path: str = "auth/state.json"):
		"""
		引数:
			storage_path (str): ブラウザの認証状態（セッション）を保存するパス。
		"""
		self.storage_path = storage_path
		os.makedirs(os.path.dirname(self.storage_path), exist_ok=True)

	async def fetch_youtube_cookies(self, output_file: str = "cookies.txt", headless: bool = True):
		"""
		YouTubeにアクセスし、Cookieを取得してNetscape形式で保存する。

		引数:
			output_file (str): 保存するファイル名。
			headless (bool): ブラウザ画面を表示するかどうか。
		"""
		await self._extract_cookies(
			site_name="YouTube",
			url="https://www.youtube.com",
			output_file=output_file,
			headless=headless,
			wait_selector="ytd-app"
		)

	async def _extract_cookies(self, site_name: str, url: str, output_file: str, headless: bool, wait_selector: str):
		"""
		共通のCookie抽出ロジック。新しいサイトを追加する場合はこのメソッドを利用する。
		"""
		async with async_playwright() as p:
			# ブラウザの起動
			browser = await p.chromium.launch(headless=headless)

			# 既存のセッション情報があれば読み込み
			if os.path.exists(self.storage_path):
				context = await browser.new_context(storage_state=self.storage_path)
			else:
				context = await browser.new_context()

			page = await context.new_page()

			try:
				print(f"[{site_name}] アクセス中: {url}")
				await page.goto(url, wait_until="networkidle")

				# 特定の要素が表示されるまで待機（読み込み完了の担保）
				await page.wait_for_selector(wait_selector, timeout=30000)

				# 人間味のある待機（スクリプト検知回避のため）
				await asyncio.sleep(2)

				# Cookieの取得
				cookies = await context.cookies()

				# Netscape形式に変換して保存
				self._save_as_netscape(cookies, output_file)

				# セッション状態を保存
				await context.storage_state(path=self.storage_path)
				print(f"[{site_name}] Cookieの保存が完了しました: {output_file}")

			except Exception as e:
				print(f"[{site_name}] エラーが発生しました: {e}")
			finally:
				await browser.close()

	def _save_as_netscape(self, cookies: List[Dict], filename: str):
		"""
		PlaywrightのCookie辞書リストをNetscape形式のテキストファイルに変換して保存する。
		"""
		with open(filename, "w", encoding="utf-8") as f:
			f.write("# Netscape HTTP Cookie File\n")
			f.write("# This file is generated by Playwright CookieManager\n\n")

			for cookie in cookies:
				# ドメインの先頭がドットで始まる必要がある場合の処理
				domain = cookie['domain']
				include_subdomains = "TRUE" if domain.startswith(".") else "FALSE"

				# 有効期限の計算（Noneの場合は1年後などに設定）
				expires = int(cookie.get('expires', time.time() + 31536000))

				# セキュア属性
				secure = "TRUE" if cookie.get('secure') else "FALSE"

				# タブ区切りで整形
				line = [
					domain,
					include_subdomains,
					cookie['path'],
					secure,
					str(expires),
					cookie['name'],
					cookie['value']
				]
				f.write("\t".join(line) + "\n")

# 単体テスト用
if __name__ == "__main__":
	manager = CookieManager()
	# ログインが必要な場合は headless=False にして手動でログインを行う
	asyncio.run(manager.fetch_youtube_cookies(headless=True))