import asyncio
import os
import time
from typing import List, Dict
from playwright.async_api import async_playwright

from module.logger import get_bot_logger
from module.options import COOKIE_FILE_PATH, USER_AGENT

logger = get_bot_logger()

class CookieManager:
    """
    Playwrightを使用して各サイトのCookieを取得・管理するクラス。
    """

    def __init__(self, storage_path: str = "auth/state.json"):
        """
        引数:
            storage_path (str): ブラウザの認証状態（セッション）を保存するパス。
        """
        self.storage_path = storage_path
        os.makedirs(os.path.dirname(self.storage_path), exist_ok=True)

    async def fetch_youtube_cookies(self, output_file: str = COOKIE_FILE_PATH, headless: bool = True):
        """
        YouTubeにアクセスし、Cookieを取得してNetscape形式で保存する。

        引数:
            output_file (str): 保存するファイル名。デフォルトはoptions.pyの設定値。
            headless (bool): ブラウザ画面を表示するかどうか。
        """
        await self._extract_cookies(
            site_name="YouTube",
            url="https://www.youtube.com",
            output_file=output_file,
            headless=headless,
            wait_selector="ytd-app"
        )

    async def _extract_cookies(self, site_name: str, url: str, output_file: str, headless: bool, wait_selector: str):
        """
        共通のCookie抽出ロジック。新しいサイトを追加する場合はこのメソッドを利用する。
        """
        async with async_playwright() as p:
            browser = await p.chromium.launch(headless=headless)

            # Bot検知を回避するため、configで指定されたUser-Agentを適用する
            context_options = {
                "user_agent": USER_AGENT
            }

            if os.path.exists(self.storage_path):
                context_options["storage_state"] = self.storage_path

            context = await browser.new_context(**context_options)
            page = await context.new_page()

            try:
                logger.info(f"[{site_name}] Cookie取得のためアクセス中: {url}")
                await page.goto(url, wait_until="networkidle")

                # 特定の要素が表示されるまで待機（読み込み完了の担保）
                await page.wait_for_selector(wait_selector, timeout=30000)

                # スクリプト検知回避のための待機
                await asyncio.sleep(2)

                cookies = await context.cookies()
                self._save_as_netscape(cookies, output_file)

                # セッション状態を保存（次回以降のログイン維持用）
                await context.storage_state(path=self.storage_path)
                logger.info(f"[{site_name}] Cookieの保存が完了しました: {output_file}")

            except Exception as e:
                logger.error(f"[{site_name}] Cookie抽出中にエラーが発生しました: {e}")
            finally:
                await browser.close()

    def _save_as_netscape(self, cookies: List[Dict], filename: str):
        """
        PlaywrightのCookie辞書リストをNetscape形式のテキストファイルに変換して保存する。
        """
        with open(filename, "w", encoding="utf-8") as f:
            f.write("# Netscape HTTP Cookie File\n")
            f.write("# This file is generated by Playwright CookieManager\n\n")

            for cookie in cookies:
                domain = cookie['domain']
                include_subdomains = "TRUE" if domain.startswith(".") else "FALSE"

                # PlaywrightのexpiresはセッションCookieの場合 -1 となるため、現在時刻から1年後に補正する
                expires_val = cookie.get('expires', -1)
                if expires_val == -1:
                    expires = int(time.time() + 31536000)
                else:
                    expires = int(expires_val)

                secure = "TRUE" if cookie.get('secure') else "FALSE"

                line = [
                    domain,
                    include_subdomains,
                    cookie['path'],
                    secure,
                    str(expires),
                    cookie['name'],
                    cookie['value']
                ]
                f.write("\t".join(line) + "\n")

# 単体テスト・手動ログイン用
if __name__ == "__main__":
    manager = CookieManager()
    # ログインが必要な場合は headless=False にして手動でログインを行う
    asyncio.run(manager.fetch_youtube_cookies(headless=True))